name: build-push-deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn -B package

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-docker-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-docker-app:latest

      - name: Deploy container to EC2 (via SSH)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker rm -f javaapp || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/java-docker-app:latest
            docker run -d -p 8080:8080 --name javaapp \
              ${{ secrets.DOCKERHUB_USERNAME }}/java-docker-app:latest
            docker ps
